# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Deployment on Dockerhub.

on:
  push:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull code
      uses: actions/checkout@v4

    - name: Setup docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker creds
      uses: docker/login-action@v2
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker build
      run: | 
        docker build -t ${{ secrets.DOCKER_REPO }} .
        docker push ${{ secrets.DOCKER_REPO }}


