export const myProjects = [
  {
    img: "https://media.istockphoto.com/id/1253862403/vector/80s-synthwave-styled-landscape-with-blue-grid-mountains-and-sun-over-canyon.jpg?s=612x612&w=0&k=20&c=2d9zWZ_Q97QbsRa_9N8FURlWWnJ_QxF7RAtHKM8Ijfo=",
    type: "Web Application",
    for: "Self",
    name: "Portfolio",
    tech: "React, SCSS, Tailwind",
    url: "aaa-portfolio.web.app",
  },
  {
    img: "https://static.vecteezy.com/system/resources/previews/006/076/790/original/10-abstract-modern-attractive-black-and-red-background-free-vector.jpg",
    type: "Web Application",
    for: "Federal Urdu University, Pakistan",
    name: "CS-Talks",
    tech: "React, JavaScript, SCSS, PHP",
    url: "fuuastcstalks.com",
  },
  {
    img: "https://images.pond5.com/attractive-background-footage-086592526_prevstill.jpeg",
    type: "Desktop Application",
    for: "Braincrop",
    name: "IceBox Pantry",
    tech: "React, Electron JS, JavaScript, ContextAPI",
    url: "",
  },
  {
    img: "https://png.pngtree.com/thumb_back/fh260/background/20190521/pngtree-3d-neon-light-abstract-background-image_111005.jpg",
    type: "Mobile Application",
    for: "Braincrop",
    name: "IceBox Pantry",
    tech: "React Native, TypeScript, Tailwind, Redux",
    url: "",
  },
  {
    img: "https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/129325364/original/afaddcb9d7dfaaf5bff7ef04101935814665ac16/design-an-attractive-background-for-your-website.png",
    type: "Web Application",
    for: "Self",
    name: "Blood Bank",
    tech: "React, JavaScript, NodeJS, Redux, ExpressJS, MongoDB, Firebase",
    url: "",
  },
  {
    img: "https://png.pngtree.com/thumb_back/fh260/background/20200714/pngtree-modern-double-color-futuristic-neon-background-image_351866.jpg",
    type: "Web Application",
    for: "Self",
    name: "Employee Management System",
    tech: ".NET Core, C#, EFC, SQL-Server",
    url: "",
  },
  {
    img: "https://png.pngtree.com/thumb_back/fh260/background/20201026/pngtree-futuristic-shape-abstract-background-chemistry-technology-concept-for-website-image_438818.jpg",
    type: "Mobile Application",
    for: "Self",
    name: "Blood Bank Mobile App",
    tech: "React Native, JavaScript, Redux, NodeJS, ExpressJS, MongoDB, Firebase",
    url: "",
  },
  {
    img: "https://i.pinimg.com/736x/ab/f7/de/abf7de18d534de6166c39fc2925259f0.jpg",
    type: "Web Application",
    for: "Self",
    name: "Copment",
    tech: "React, TypeScript, Redux, Node, Express, MongoDB",
    url: "",
  },
  {
    img: "https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8fA%3D%3D&w=1000&q=80",
    type: "Server Application",
    for: "AGS",
    name: "NFT Inventory Management",
    tech: "TypeScript, Node, Express, MongoDB",
    url: "",
  },
  {
    img: "https://png.pngtree.com/thumb_back/fh260/background/20201123/pngtree-digital-technology-low-poly-design-image_499020.jpg",
    type: "Server Application",
    for: "AGS",
    name: "Live Chat for NFT Trading",
    tech: "TypeScript, Node, Express, MongoDB, Socket.io",
    url: "",
  },
  {
    img: "https://www.pixelstalk.net/wp-content/uploads/images6/Aesthetic-Neon-Wallpaper-City.jpg",
    type: "Mobile Application",
    for: "Self",
    name: "Weather Mobile App",
    tech: "React Native, JavaScript",
    url: "",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB7jv1qIxtYApS6O4rPw9u_O36YJTgJJv_8c3PkSXiCg06JOAO7Fd7as8agpw_8B8JM90&usqp=CAU",
    type: "Web Application",
    for: "Self",
    name: "COVID-19 Tracker",
    tech: "React, JavaScript",
    url: "",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQri_rcUUg49ezCaSJA9zHKAJS8nINTZLS1mpwuSfhTnKOqtt6nPlDz1AS2KoypQiNxNYM&usqp=CAU",
    type: "Web  Application",
    for: "AR Distributors",
    name: "AR-Enterprises",
    tech: "React, JavaScript",
    url: "",
  },
];
