export const myProjects = [
  {
    img: "",
    type: "Web Application",
    for: "Self",
    name: "Portfolio",
    tech: "React, SCSS, Tailwind",
    url: "aaa-portfolio.web.app",
  },
  {
    img: "",
    type: "Web Application",
    for: "Federal Urdu University, Pakistan",
    name: "CS-Talks",
    tech: "React, JavaScript, SCSS, PHP",
    url: "fuuastcstalks.com",
  },
  {
    img: "",
    type: "Desktop Application",
    for: "Braincrop",
    name: "IceBox Pantry",
    tech: "React, Electron JS, JavaScript, ContextAPI",
    url: "",
  },
  {
    img: "",
    type: "Mobile Application",
    for: "Braincrop",
    name: "IceBox Pantry",
    tech: "React Native, TypeScript, Tailwind, Redux",
    url: "",
  },
  {
    img: "",
    type: "Web Application",
    for: "Self",
    name: "Blood Bank",
    tech: "React, JavaScript, NodeJS, Redux, ExpressJS, MongoDB, Firebase",
    url: "",
  },
  {
    img: "",
    type: "Web Application",
    for: "Self",
    name: "Employee Management System",
    tech: ".NET Core, C#, EFC, SQL-Server",
    url: "",
  },
  {
    img: "",
    type: "Mobile Application",
    for: "Self",
    name: "Blood Bank Mobile App",
    tech: "React Native, JavaScript, Redux, NodeJS, ExpressJS, MongoDB, Firebase",
    url: "",
  },
  {
    img: "",
    type: "Web Application",
    for: "Self",
    name: "Copment",
    tech: "React, TypeScript, Redux, Node, Express, MongoDB",
    url: "",
  },
  {
    img: "",
    type: "Server Application",
    for: "AGS",
    name: "NFT Inventory Management",
    tech: "TypeScript, Node, Express, MongoDB",
    url: "",
  },
  {
    img: "",
    type: "Server Application",
    for: "AGS",
    name: "Live Chat for NFT Trading",
    tech: "TypeScript, Node, Express, MongoDB, Socket.io",
    url: "",
  },
  {
    img: "",
    type: "Mobile Application",
    for: "Self",
    name: "Weather Mobile App",
    tech: "React Native, JavaScript",
    url: "",
  },
  {
    img: "",
    type: "Web Application",
    for: "Self",
    name: "COVID-19 Tracker",
    tech: "React, JavaScript",
    url: "",
  },
  {
    img: "",
    type: "Web  Application",
    for: "AR Distributors",
    name: "AR-Enterprises",
    tech: "React, JavaScript",
    url: "",
  },
];
